### ISSUE TITLE
多选框显示问题

### ISSUE THREAD

**Issue by LGY07** [lingrottin/MC-HEXColor-Gadient-Generator#1]
# 为什么多选框不是圆角？
（从readme的图以及本人使用时发现）在Windows 11系统中，窗口以及多选框应为圆角，但是在软件中的多选框不是圆角（窗口正常）

**Comment by LGY07** [comment]
按钮也有相同的问题

**Comment by lingrottin** [comment]
暂不明白原理，我也有同样的疑问。可能是WPF特色？反正不影响使用。
